spring.application.name=backend

# DB
spring.datasource.url=jdbc:postgresql://localhost:5432/revertz
spring.datasource.username=shashwat
spring.datasource.password=dbpass
spring.datasource.driver-class-name=org.postgresql.Driver

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.format_sql=true


# Logging
logging.file.name=logs/spring.log
logging.include-application-group=false
logging.include-application-name=false
logging.pattern.file=%d{yyyy-MM-dd HH:mm:ss.SSS} %-5level : %msg%n